# Generated by Django 6.0.7 on 2026-08-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0003_appointment_appointment_time_appointment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confidence_score',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='distance',
            field=models.CharField(default='1.2 km', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_or_counter',
            field=models.CharField(blank=True, default='Counter 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_wait_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization_name',
            field=models.CharField(default='City General Hospital', max_length=100),
        ),
    ]
